package com.yss.acs.mock.webservice.webservice7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-26T10:00:25.896+08:00
 * Generated source version: 3.2.14
 *
 */
@WebServiceClient(name = "BondFromACSService",
                  wsdlLocation = "http://127.0.0.1:10110/acs/services/com/yss/acs/api/publishservice/webservice/BondFromACSService?wsdl",
                  targetNamespace = "http://webservice.publishservice.api.acs.yss.com/")
public class BondFromACSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.publishservice.api.acs.yss.com/", "BondFromACSService");
    public final static QName BondFromACSServicePort = new QName("http://webservice.publishservice.api.acs.yss.com/", "BondFromACSServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:10110/acs/services/com/yss/acs/api/publishservice/webservice/BondFromACSService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BondFromACSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:10110/acs/services/com/yss/acs/api/publishservice/webservice/BondFromACSService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BondFromACSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BondFromACSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BondFromACSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BondFromACSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BondFromACSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BondFromACSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BondFromACSServicePortType
     */
    @WebEndpoint(name = "BondFromACSServicePort")
    public BondFromACSServicePortType getBondFromACSServicePort() {
        return super.getPort(BondFromACSServicePort, BondFromACSServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BondFromACSServicePortType
     */
    @WebEndpoint(name = "BondFromACSServicePort")
    public BondFromACSServicePortType getBondFromACSServicePort(WebServiceFeature... features) {
        return super.getPort(BondFromACSServicePort, BondFromACSServicePortType.class, features);
    }

}
