package com.yss.acs.mock.webservice.webservice7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-26T10:00:25.828+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "http://webservice.publishservice.api.acs.yss.com/", name = "BondFromACSServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BondFromACSServicePortType {

    @WebMethod
    @RequestWrapper(localName = "findBondFromACS", targetNamespace = "http://webservice.publishservice.api.acs.yss.com/", className = "com.yss.acs.mock.webservice.webservice7.FindBondFromACS")
    @ResponseWrapper(localName = "findBondFromACSResponse", targetNamespace = "http://webservice.publishservice.api.acs.yss.com/", className = "com.yss.acs.mock.webservice.webservice7.FindBondFromACSResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.publishservice.api.acs.yss.com/")
    public java.lang.String findBondFromACS(
        @WebParam(name = "arg0", targetNamespace = "http://webservice.publishservice.api.acs.yss.com/")
        java.lang.String arg0
    );
}
