package com.yss.acs.mock.webservice.webservice7;

import javax.jws.WebService;


/**
 * generated by mock-platform 
 */
@WebService(targetNamespace = "http://webservice.publishservice.api.acs.yss.com/", serviceName = "BondFromACSServicePortType", endpointInterface = "com.yss.acs.mock.webservice.webservice7.BondFromACSServicePortType")
public class BondFromACSServicePortTypeMockImpl implements BondFromACSServicePortType {

    private java.util.Map<String, Object> mockResultMap = new java.util.HashMap<String, Object>();

    public void setMockPlatformResult(java.util.Map<String, Object> mockResultMap) {
        this.mockResultMap = mockResultMap;
    }

    public Object getMockPlatformResult(String methodName) {
        Object obj = mockResultMap.get(methodName);
        obj = com.yss.acs.mock.util.MockResultUtil.getMockResultObject(obj);
        return obj;
    }


    @Override
    public java.lang.String findBondFromACS(
        java.lang.String arg0
    ) {
        String methodName = Thread.currentThread().getStackTrace()[1].getMethodName();
        return (java.lang.String) getMockPlatformResult(methodName);
    }

}
