package com.yss.acs.mock.webservice.webservice1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-09-17T17:11:12.852+08:00
 * Generated source version: 3.2.14
 *
 */
@WebServiceClient(name = "multiTGServiceService",
                  wsdlLocation = "http://127.0.0.1:10110/cps/multiTGService?wsdl",
                  targetNamespace = "http://www.primeton.com/multiTGService")
public class MultiTGServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.primeton.com/multiTGService", "multiTGServiceService");
    public final static QName MultiTGServicePort = new QName("http://www.primeton.com/multiTGService", "multiTGServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:10110/cps/multiTGService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MultiTGServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:10110/cps/multiTGService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MultiTGServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MultiTGServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiTGServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MultiTGServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MultiTGServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MultiTGServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MultiTGService
     */
    @WebEndpoint(name = "multiTGServicePort")
    public MultiTGService getMultiTGServicePort() {
        return super.getPort(MultiTGServicePort, MultiTGService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultiTGService
     */
    @WebEndpoint(name = "multiTGServicePort")
    public MultiTGService getMultiTGServicePort(WebServiceFeature... features) {
        return super.getPort(MultiTGServicePort, MultiTGService.class, features);
    }

}
