package com.yss.acs.mock.webservice.webservice4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-09-18T16:41:39.896+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "UnifiedAuthenSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface UnifiedAuthenSoap {

    @WebMethod(operationName = "GenerateMessagePWD", action = "http://tempuri.org/GenerateMessagePWD")
    @RequestWrapper(localName = "GenerateMessagePWD", targetNamespace = "http://tempuri.org/", className = "com.yss.acs.mock.webservice.webservice4.GenerateMessagePWD")
    @ResponseWrapper(localName = "GenerateMessagePWDResponse", targetNamespace = "http://tempuri.org/", className = "com.yss.acs.mock.webservice.webservice4.GenerateMessagePWDResponse")
    @WebResult(name = "GenerateMessagePWDResult", targetNamespace = "http://tempuri.org/")
    public com.yss.acs.mock.webservice.webservice4.GetMessagePWDModel generateMessagePWD(
        @WebParam(name = "authorizedName", targetNamespace = "http://tempuri.org/")
        java.lang.String authorizedName,
        @WebParam(name = "authorizedKey", targetNamespace = "http://tempuri.org/")
        java.lang.String authorizedKey,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "timeStamp", targetNamespace = "http://tempuri.org/")
        java.lang.String timeStamp
    );

    @WebMethod(operationName = "Authenticate", action = "http://tempuri.org/Authenticate")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://tempuri.org/", className = "com.yss.acs.mock.webservice.webservice4.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://tempuri.org/", className = "com.yss.acs.mock.webservice.webservice4.AuthenticateResponse")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://tempuri.org/")
    public com.yss.acs.mock.webservice.webservice4.AuthenticationModel authenticate(
        @WebParam(name = "authorizeType", targetNamespace = "http://tempuri.org/")
        java.lang.String authorizeType,
        @WebParam(name = "authorizeName", targetNamespace = "http://tempuri.org/")
        java.lang.String authorizeName,
        @WebParam(name = "authorizeKey", targetNamespace = "http://tempuri.org/")
        java.lang.String authorizeKey,
        @WebParam(name = "messageKey", targetNamespace = "http://tempuri.org/")
        java.lang.String messageKey
    );
}
