package com.yss.acs.mock.webservice.webservice4;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-09-18T16:41:39.935+08:00
 * Generated source version: 3.2.14
 *
 */
@WebServiceClient(name = "UnifiedAuthen",
                  wsdlLocation = "http://127.0.0.1:10110/UnifiedAuthen.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class UnifiedAuthen extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "UnifiedAuthen");
    public final static QName UnifiedAuthenSoap12 = new QName("http://tempuri.org/", "UnifiedAuthenSoap12");
    public final static QName UnifiedAuthenSoap = new QName("http://tempuri.org/", "UnifiedAuthenSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:10110/UnifiedAuthen.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UnifiedAuthen.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:10110/UnifiedAuthen.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UnifiedAuthen(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UnifiedAuthen(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnifiedAuthen() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UnifiedAuthen(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UnifiedAuthen(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UnifiedAuthen(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UnifiedAuthenSoap
     */
    @WebEndpoint(name = "UnifiedAuthenSoap12")
    public UnifiedAuthenSoap getUnifiedAuthenSoap12() {
        return super.getPort(UnifiedAuthenSoap12, UnifiedAuthenSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnifiedAuthenSoap
     */
    @WebEndpoint(name = "UnifiedAuthenSoap12")
    public UnifiedAuthenSoap getUnifiedAuthenSoap12(WebServiceFeature... features) {
        return super.getPort(UnifiedAuthenSoap12, UnifiedAuthenSoap.class, features);
    }


    /**
     *
     * @return
     *     returns UnifiedAuthenSoap
     */
    @WebEndpoint(name = "UnifiedAuthenSoap")
    public UnifiedAuthenSoap getUnifiedAuthenSoap() {
        return super.getPort(UnifiedAuthenSoap, UnifiedAuthenSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnifiedAuthenSoap
     */
    @WebEndpoint(name = "UnifiedAuthenSoap")
    public UnifiedAuthenSoap getUnifiedAuthenSoap(WebServiceFeature... features) {
        return super.getPort(UnifiedAuthenSoap, UnifiedAuthenSoap.class, features);
    }

}
